### ISSUE TITLE
some ideas and dependencies

### ISSUE THREAD

**Issue by mmariani** [b-ryan/powerline-shell#296]
Hi,

I'd like to try (when I have some free time) a few features like configuration validation, yaml, true color, etc.

Now, given the peculiar nature of the application (i.e. no prompt if something breaks), and the fact that locally installed eggs can interfere with other applications, would you rather limit the package dependencies and include third party code in this repository?

I'm not proposing any feature right now, just thinking out loud. Thanks

**Comment by jceaser** [comment]
I would agree to limit third party libs as much as possible.

**Comment by b-ryan** [comment]
Yes I am aiming to not add any additional dependencies unless strictly necessary - this would eliminate yaml, which I'd be against anyway just due to it adding additional complexity.

At this point in the project I am already worried too many features and options exist and I need to start thinking about trimming that down.
