### ISSUE TITLE
Directory address name change

### ISSUE THREAD

**Issue by sbmaruf** [b-ryan/powerline-shell#345]
Sometimes while working with large directory we often rename the shell address by changing PS1,

```
if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]${PROMPT:-\w}\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:${PROMPT:-\w}\$ '
fi
```
Code from "https://askubuntu.com/questions/987843/how-to-rename-the-shell-current-working-directory"

Here, by changing PROMPT we can rename the current address. 
While using the power-shell, obviously we are renaming PS1 to powershell. How can I get this renaming feature in power-shell?

**Comment by b-ryan** [comment]
Good question. There is not any way to make this happen in powerline-shell currently. I am working on #365 which adds a segment that will allow reading arbitrary environment variables. But it does not have any support for using the fallback syntax here. Perhaps either instead of the `env` segment or in addition to it, there could be a `raw` segment which just takes some raw string that will be put into the prompt. In your case, the value of the `raw` segment would be `${PROMPT:-\w}`

Since none of that exists at the moment, perhaps the `max_depth` configuration might be sufficient for you? See https://github.com/b-ryan/powerline-shell#segment-configuration
