### ISSUE TITLE
How do I make the prompt start on a new line? Which config file am I looking for?

### ISSUE THREAD

**Issue by mon0theist** [b-ryan/powerline-shell#439]
Details here: https://www.reddit.com/r/archlinux/comments/9wm8h4/powerline_and_bash_can_i_make_my_powerline_prompt/

I just want to make my prompt start on a new line and I can't figure out how. Supposedly I'm looking for a config file that looks like this:

https://github.com/ffried/powerline-shell/blob/30f2124db18e2d186ee7b79fbf60aa7d7ab0230a/config.py.dist#L52

But I can't find anything that resembles this anywhere.

Can someone tell me what specific config file I'm looking for and where do I add/uncomment the "newline," ?

**Comment by b-ryan** [comment]
Hey @mon0theist sorry for confusion around this. The config file isn't on your system by default, you have to create one in order to customize it. Put the config in `~/.config/powerline-shell/config.json`. We don't currently have a way to add a global config file for all users but it's something that will be coming (PR is welcome). You can see the command to generate a default config which you can then customize [here](https://github.com/b-ryan/powerline-shell#config-file).

**Comment by mon0theist** [comment]
Doesn't work :( 

Bash tells me that "powerline-shell" is not a valid command. I installed from Arch repos rather than cloning from Github so maybe that's causing some differences.

I'll see if I can figure out where to put your example config in your link there

**Comment by b-ryan** [comment]
I wonder if you are running into issues (which we have seen before) with mixing up the "powerline" project and "powerline-shell" which are unfortunately named in a way to cause confusion. The fact you have a `powerline_root` would suggest this.

For this project we recommend installing with `pip` and I wouldn't expect there to be an Arch package for it. Can you elaborate on how you have installed it?

**Comment by mon0theist** [comment]
Oh yeah I just have the Arch package installed, I didn't use `pip`. 

Here is the Arch Wiki page for it, if that helps: https://wiki.archlinux.org/index.php/Powerline

**Comment by mon0theist** [comment]
Sorry @b-ryan, I just realized this isn't the upstream package/dev that I actually needed. I was actually looking for https://github.com/powerline/powerline

I will close this issue
